### ISSUE TITLE
What is the use for this application

### ISSUE THREAD

**Issue by alwinaugustin** [benyaminahmed/nft-image-generator#11]
I successfully ran the application and it has generated some weird images in the `images` folder. Now I am not sure about the next steps to be followed. Can we upload these images to Opensea? I don't think no one will buy these images and all of them look similar.

Anyone here know what to do ?

**Comment by BuddyBob** [comment]
No. I pretty much asked the same question. If he included all of his code, it would be too easy for others to make new weird whale combinations.  And obviously, he wouldn't want anybody doing that.

**Comment by ThyGrishnackh** [comment]
> No. I pretty much asked the same question. If he included all of his code, it would be too easy for others to make new weird whale combinations. And obviously, he wouldn't want anybody doing that.

Heya! He just gave you "all of his code". You don't need more to create your own weird whale or whatever nft you like. Just read thoroughly through the code, and you'll figure it out in a matter of minutes
