### ISSUE TITLE
editin python code w/ 4 variables 

### ISSUE THREAD

**Issue by gkc98** [benyaminahmed/nft-image-generator#18]
hi ,
im really new this and i need some help. i change the background to png instead of jpg, because my file was a png. But i'm getting this error.would really appreciate some troubleshooting help 

im1 = Image.open(f'./layers/background/{background_files[item["background"]]}.png').convert('RGBA')
      4     im2 = Image.open(f'./layers/mouth/{mouth_files[item["mouth"]]}.png').convert('RGBA')
      5     im3 = Image.open(f'./layers/spoon/{spoon_files[item["spoon"]]}.png').convert('RGBA')

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/PIL/Image.py in open(fp, mode, formats)
   2966 
   2967     if filename:
-> 2968         fp = builtins.open(filename, "rb")
   2969         exclusive_fp = True
   2970 

FileNotFoundError: [Errno 2] No such file or directory: './layers/background/purple.png'

**Comment by benyaminahmed** [comment]
This looks like that directory does not exist, check the spelling on all the different paths like layers/backgrounds.
