### ISSUE TITLE
How to run application

### ISSUE THREAD

**Issue by dalezorz** [benyaminahmed/nft-image-generator#2]
Hi there

How does one run this generator within Jupyter?
I've used the generate.ipynb file within Jupyter but nothing happens. It's seems to throw some sort of error. Please if you can maybe explain in more details or upload some screenshots of what the code should look like in order to function?

Thank you.

**Comment by victorquanlam** [comment]
I have the same question as well.

**Comment by benyaminahmed** [comment]
Do you have a specific error message? The program should work as soon as you check it out and press run all.

**Comment by BuddyBob** [comment]
If you have VScode, you can just git clone the repo and open it in the VScode editor. Then just run the `generate.ipynb` file. 

<img width="691" alt="Screen Shot 2021-08-29 at 7 08 22 PM" src="https://user-images.githubusercontent.com/66140321/131275675-a9f2dd96-5bc1-46ab-b09c-c27a13fb4b75.png">

**Comment by dalezorz** [comment]
I receive the following error when running the code via Jupyter. 
I did manage to run the code via VScore and that worked fine. Thank you for all the replies :)
![nft](https://user-images.githubusercontent.com/75077211/131320959-35f49000-8af7-4a31-86a2-649dabd870f7.jpg)
