### ISSUE TITLE
Thankyou

### ISSUE THREAD

**Issue by pradyumncs** [benyaminahmed/nft-image-generator#20]
made  my 10000 images with 5 layers . The hard part was the Image.alpha_composite 
love from India . You are a legend in this country

you introduced me to NFT actually
Do continue coding

**Comment by CHayford** [comment]
Hi Pradyumns, 

That's amazing. How did you managed to change the Image.alpha_composite, really struggling with this part. If you have any advice that would be appreciate.

Thanks,

**Comment by benyaminahmed** [comment]
Can you post your error here @CHayford? At this stage, people usually get an error as the images are not the same size.

**Comment by benyaminahmed** [comment]
Hi @CHayford, closing this issue as no response. Feel free to contact me if you still have an issue.
