### ISSUE TITLE
I need a small bit of guidance

### ISSUE THREAD

**Issue by Ryanno2021** [benyaminahmed/nft-image-generator#22]
Hello,

Thanks for generating the code. I'm having some difficulties running it. I have tried following the steps you have put out - I installed python, pip, python pillow and have tried several times to get a ui for jupyter notebook. I settled with JupyterLab. However, I don't know how to duplicate my nft image., or the ideal commands to run. Can I have some guidance?

Thanks!

**Comment by Mpellet771** [comment]
I have a similar question: the program seems to require that the Execute: command have the number of images that I want populated in several places. Is this where I put how many copies I want? thanks.

**Comment by benyaminahmed** [comment]
The number of images you want to create is specified in a variable called TOTAL_IMAGES and in the sample it is currently set at 30. I would suggest before you try to create your own images, just get the program to run using my sample and have a play around with it. If you get a specific error, post the error.
