### ISSUE TITLE
Maximum recursion depth reached

### ISSUE THREAD

**Issue by zachalbert** [benyaminahmed/nft-image-generator#24]
Thanks a lot for this awesome notebook! One problem I'm running into is I'm hitting the maximum recursion depth when trying to generate more than about 200 images. My setup has 8 layers, with 1-5 variants in each, but if I set `TOTAL_IMAGES` higher than about 250, I hit the limit. I'm trying to generate 10,000 images, so kind of stuck.

This is the error I'm seeing:

```
  File "/Users/zac/.pyenv/versions/3.9.4/lib/python3.9/random.py", line 498, in choices
    return [population[bisect(cum_weights, random() * total, 0, hi)]
  File "/Users/zac/.pyenv/versions/3.9.4/lib/python3.9/random.py", line 498, in <listcomp>
    return [population[bisect(cum_weights, random() * total, 0, hi)]
RecursionError: maximum recursion depth exceeded in comparison
```

One detail is I used nbconvert to convert the notebook to a python script so it can be run via script.

I did find to add this line:

```
import sys
sys.setrecursionlimit(65532)
```

However, that just changes the error to `segmentation fault` when I try to go higher than 250. Any thoughts?

**Comment by benyaminahmed** [comment]
You usually get this error when the number of tokens you are trying to produce is greater than what your set can support. Try reducing the number here: TOTAL_IMAGES = 30
