### ISSUE TITLE
IMAGES_BASE_URI

### ISSUE THREAD

**Issue by justin-david** [benyaminahmed/nft-image-generator#27]
Not so much an issue, more a question. 

IMAGES_BASE_URI

Under the meta_data generation line, this needs to be input manually correct? So if I was to upload onto IPFS, I would need to manually go in and add the IPFS link.

Thanks!

**Comment by benyaminahmed** [comment]
Images Base URI is a place holder. When  you generate your images, it will create all the metadata and point it to this place holder. After you have uploaded the images to IPFS, grab the IPFS link and open all your metadata files in something like VS Code and do a search and replace. 

This is what the final metadata looks like:
https://github.com/benyaminahmed/weird-whales-images/blob/main/metadata/0
