### ISSUE TITLE
Recursion error 

### ISSUE THREAD

**Issue by jackclearman** [benyaminahmed/nft-image-generator#28]
When I set the TOTAL_IMAGES = 10000 

I get a recursion error:

RecursionError       Traceback (most recent call last)
/var/folders/j7/byspn9bd3rddg31124_fldnm0000gn/T/ipykernel_2323/1847067360.py in <module>
     28 for i in range(TOTAL_IMAGES):
     29 
---> 30     new_trait_image = create_new_image()
     31 
     32     all_images.append(new_trait_image)

/var/folders/j7/byspn9bd3rddg31124_fldnm0000gn/T/ipykernel_2323/1847067360.py in create_new_image()
     20 
     21     if new_image in all_images:
---> 22         return create_new_image()
     23     else:
     24         return new_image

... last 1 frames repeated, from the frame below ...

/var/folders/j7/byspn9bd3rddg31124_fldnm0000gn/T/ipykernel_2323/1847067360.py in create_new_image()
     20 
     21     if new_image in all_images:
---> 22         return create_new_image()
     23     else:
     24         return new_image

RecursionError: maximum recursion depth exceeded in comparison

Setting the sys recursion limit to 10k [sys.setrecursionlimit(10000)] doesn't make a difference, in fact the error is throw with any image # above 5775

Any ideas? Thanks!

**Comment by benyaminahmed** [comment]
Hi Jackclearman, this happens when the number of images you are trying to create exceeds the capacity that your traits support. Either reduce the number of images you are creating or create more traits.
