### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ImaEternal** [benyaminahmed/nft-image-generator#30]
Is this script like an all in one for my NFT project so I can upload to opensea. It has per item rarity right? Does it have to equal 100% because I have 32 hairstyles and that would mean that each would be 3% chance. Can you explain further?

**Comment by number435398** [comment]
From what I can see, its up to you to ensure the numbers add up to 100% as located in generate.ipynb

**Comment by benyaminahmed** [comment]
This script only contains the code for creating the NFT images. If you want to also create a web app for minting them, have a look at Alchemy Docs. https://docs.alchemy.com/alchemy/tutorials/nft-minter

You can also look at the BBCo repo. https://github.com/vortextemporum/BoringBananasCompany/
