### ISSUE TITLE
The number of weights does not match the population

### ISSUE THREAD

**Issue by projectfive0** [benyaminahmed/nft-image-generator#32]
I am getting an error when trying to add more than the three layers that are already being used. I get the error 'The number of weights does not match the population', would you mind helping me out?

**Comment by Pokesi** [comment]
The amount of probabilities should be the same as the amount of traits

**Comment by projectfive0** [comment]
All I did was add another trait category onto each part of the code, where would i change the amount of probabilities?
I have done the same weights for all of the traits [30,,40,15,10,5]

**Comment by LMA033** [comment]
Did you make it ? i have same error

**Comment by wsasdsda** [comment]
As a beginner,I still can't get your answer,could you please be a little more specific?
