### ISSUE TITLE
help me please

### ISSUE THREAD

**Issue by LMA033** [benyaminahmed/nft-image-generator#37]
hi, am getting this error every time i want to generate trails: [ValueError: The number of weights does not match the population]()

**Comment by Pokesi** [comment]
learn python lol

**Comment by LMA033** [comment]
am trying LOL

**Comment by PumpSnooki** [comment]
> hi, am getting this error every time i want to generate trails: ValueError: The number of weights does not match the population

You have to have the same exact number of items to weights in the top of your generator code. Here is an example below.

background = ["Apple", "Blue", "Dark Cerulean",                            
              "Green", "Grey", "Nordic",                                   
              "Orange", "Peach", "Persian Indigo",                         
              "Pink", "Port Gore", "Purple",                               
              "Red", "Yellow"]                                             

background_weights = [0, 14, 0,                                            
                      14, 12, 10,                                          
                      12, 0, 10,                                            
                      12, 12, 14,                                           
                      0, 0   ]

**Comment by PumpSnooki** [comment]
> learn python lol

The world is full of assholes, you don't have to be another one.

**Comment by PumpSnooki** [comment]
> > > hi, am getting this error every time i want to generate trails: ValueError: The number of weights does not match the population
> > 
> > 
> > You have to have the same exact number of items to weights in the top of your generator code. The weight has to be equal 100+ as well. Here is an example below.
> > background = ["Apple", "Blue", "Dark Cerulean", "Green", "Grey", "Nordic", "Orange", "Peach", "Persian Indigo", "Pink", "Port Gore", "Purple", "Red", "Yellow"]
> > background_weights = [0, 14, 0, 14, 12, 10, 12, 0, 10, 12, 12, 14, 0, 0 ]
> 
> Thanks ! I found myself but I forgot to close this ticket. Can you please give me any tips about IPFS ?

Sure, add me on discord and I will try and help you the best I can. -> ( PumpSnooki#7251 )
