### ISSUE TITLE
How are you making the whale images? 

### ISSUE THREAD

**Issue by BuddyBob** [benyaminahmed/nft-image-generator#6]
I've looked everywhere in your code and can only find squares circles and images. I don't see where you made the accessories like the hats, cigars, and eyes. And where are your whale bases located?

**Comment by benyaminahmed** [comment]
This example is a simplified version. I haven't included the base image of my whales and traits. The reason was because then it would be too easy for people to generate more whale images. I created my whale images and traits using https://www.pixilart.com/

**Comment by BuddyBob** [comment]
Makes total sense! I'm 12 years old (check my github profile lmao - imature stuff) and would definitely love to give this a try too. But obviously, instead of whales, I might do ladybugs and other animals like that (maybe an elephant?). I've given it a try using Pillow and haven't got much luck. Do you mind giving me a few pointers on how I could add accessories to my base image? Or like putting a background and foreground into my image? That would be really **awesome**.  

Also, if you feel like not sharing anything about your project, I totally understand (I wouldn't want people stealing my work either). Simply I want to give this a shot, and I would really appreciate it if you could give me a few pointers.

**Comment by fellahi-ali** [comment]
hey awesome @benyaminahmed & @BuddyBob
I'm also interested to try this, and looking for resources, although I'm 38 years old 😅😅
I found this YouTube video  https://www.youtube.com/watch?v=p36tXHX1JD8
maybe it would be helpful
waiting for @benyaminahmed's answer 😉
