### ISSUE TITLE
Missing module "PIL"

### ISSUE THREAD

**Issue by willi8mm** [benyaminahmed/nft-image-generator#9]
![image](https://user-images.githubusercontent.com/89804025/131392960-f02dbc63-e7b9-47bc-a2b0-fb505a9f3a1d.png)

Module Pillow is installed but saying it isn't. Anyone know why?

**Comment by BuddyBob** [comment]
Have you followed the README documentation? 
Install PIP
```
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py

python get-pip.py
```
use to install pillow
```
pip install pillow
```
if that does not work try 
```
pip3 install pillow
```
or
```
python3 -m pip install --upgrade Pillow
```
Hope this helped. 
https://github.com/benyaminahmed/nft-image-generator/blob/main/README.md

**Comment by benyaminahmed** [comment]
Thanks for the support @BuddyBob.
